### ISSUE TITLE
As a USER I can ADD chips to the order, so I can checkout chips

### ISSUE THREAD

**Issue by muhamrif** [muhamrif/Whole-Lotta-Sub#10]
- [ ] Ask user which chips they would like to add to order from the menu:
- [ ] DIFFERENT VARIETIES OF CHIPS:
1. Lays
2.  Pringles
3.  Potato Chips
- [ ] PRICE FOR CHIPS:
1.  $1.50
- [ ] make the Chips object, and add that to the chips array which will be used to instantiate the order object.

**Comment by akhilsomaiya07** [comment]
DIFFERENT VARIETIES OF CHIPS:

- [ ] Lays
- [ ] Pringles
- [ ] Potato Chips
