### ISSUE TITLE
As a USER,I want to have an option to see multiple breads, so I can SELECT bread for my sandwich

### ISSUE THREAD

**Issue by muhamrif** [muhamrif/Whole-Lotta-Sub#2]
STEPS:

- [x] Create a **Bread** class.
- [x] add the option to select bread in the **ADD SANDWICH** menu
- [x] TYPES OF BREAD AVAILABLE:
1. White
2. Wheat
3. Rye
4. Wrap
- [x] DIFFERENT PRICES OF BREAD
1. (4" - small) $5.50
2. (8" - medium) $7.00
3. (12" - premium) $8.50
- [x] after USER selects the type of bread, instantiate a bread object using the user input.
- [x] use the newly created bread for the sandwich object.

**Comment by muhamrif** [comment]
STEPS:

- [ ] Create a **Bread** class.
- [ ] add the option to select bread in the **ADD SANDWICH** menu
- [ ] after USER selects the type of bread, instantiate a bread object using the user input.
- [ ] use the newly created bread for the sandwich object.

**Comment by akhilsomaiya07** [comment]
TYPES OF BREAD AVAILABLE

- [ ] White
- [ ] Wheat
- [ ] Rye
- [ ] Wrap

**Comment by akhilsomaiya07** [comment]
DIFFERENT PRICES OF BREAD

- [ ] (4" - small) $5.50
- [ ] (8" - medium) $7.00
- [ ] (12" - premium) $8.50
