### ISSUE TITLE
As a USER,I want to see different options for meats, so that I can SELECT meat for my sandwich

### ISSUE THREAD

**Issue by muhamrif** [muhamrif/Whole-Lotta-Sub#3]
- [ ] As a USER, I can SELECT type of meat for my sandwhich
- [ ] As a USER, I can ADD extra meat to my sandwhich

STEPS:

- [ ]  Create a premium topping class.
- [ ]  add the option to select meat in the ADD SANDWICH menu
- [ ] TYPES OF MEAT:
1. Steak
2. Ham
3. Salami
4. Roast Beef
5. Chicken
6. Bacon

- [ ] DIFFERENT PRICES AND SIZES FOR MEAT:
1. (small - 4") - $1.00
2. (medium - 8") - $2.00
3. (Premium - 12") - $3.00

- [ ]  after USER selects the meat, instantiate a premium topping object using the user input.
- [ ]  use the newly created premium toppings for the sandwich object.

**Comment by akhilsomaiya07** [comment]
STEPS:
- [ ]  Create a premium topping class.
- [ ]  add the option to select meat in the ADD SANDWICH menu
- [ ]  after USER selects the meat, instantiate a premium topping object using the user input.
- [ ]  use the newly created premium toppings for the sandwich object.

**Comment by akhilsomaiya07** [comment]
TYPES OF MEAT:

- [ ] Steak
- [ ] Ham
- [ ] Salami
- [ ] Roast Beef
- [ ] Chicken
- [ ] Bacon

**Comment by akhilsomaiya07** [comment]
DIFFERENT PRICES AND SIZES FOR MEAT:

- [ ] (small - 4") - $1.00
- [ ] (medium - 8") - $2.00
- [ ] (Premium - 12") - $3.00

**Comment by akhilsomaiya07** [comment]
DIFFERENT PRICES AND SIZES FOR EXTRA MEAT:

- [ ] (small - 4") - .50
- [ ] (medium - 8") - $1.00
- [ ] (Premium - 12") - $1.50
