### ISSUE TITLE
As a USER,I want to see different options for cheese, so that I can SELECT cheese for my sandwich

### ISSUE THREAD

**Issue by muhamrif** [muhamrif/Whole-Lotta-Sub#4]
- [x] Create a PremiumTopping class.
- [x]  add the option to select Cheese in the ADD SANDWICH menu
- [x] DIFFERENT VARIETY OF CHEESE:
1. American
2. Provolone
3. Cheddar
4. Swiss
- [x] DIFFERENT PRICES AND SIZES FOR CHEESE:
1. (small - 4") - .75
2. (medium - 8") - $ 1.50
3. (premium - 12") - $2.25
- [x] DIFFERENT PRICES AND SIZES FOR EXTRA CHEESE:
1. (small - 4") - .30
2. (medium - 8") - .60
3. (premium - 12") - .90
- [x]  after USER selects the type of Cheese, instantiate a PremiumTopping object using the user input.
- [x]  use the newly created Cheese for the sandwich object.
- [x]  ask user if they want extra cheese, if yes, then make pass the ExtraCheese boolean as TRUE for sandwich instantiation, else false.

**Comment by muhamrif** [comment]
STEPS:

- [ ]  Create a PremiumTopping class.
- [ ]  add the option to select Cheese in the ADD SANDWICH menu
- [ ]  after USER selects the type of Cheese, instantiate a PremiumTopping object using the user input.
- [ ]  use the newly created Cheese for the sandwich object.
- [ ]  ask user if they want extra cheese, if yes, then make pass the ExtraCheese boolean as TRUE for sandwich instantiation, else false.

**Comment by akhilsomaiya07** [comment]
DIFFERENT VARIETY OF CHEESE:

- [ ] American
- [ ] Provolone
- [ ] Cheddar
- [ ] Swiss

**Comment by akhilsomaiya07** [comment]
DIFFERENT PRICES AND SIZES FOR CHEESE:

- [ ] (small - 4") - .75
- [ ] (medium - 8") - $ 1.50
- [ ] (premium - 12") - $2.25

**Comment by akhilsomaiya07** [comment]
DIFFERENT PRICES AND SIZES FOR EXTRA CHEESE:

- [ ] (small - 4") - .30
- [ ] (medium - 8") - .60
- [ ] (premium - 12") - .90
