### ISSUE TITLE
As a USER, I want to see different types of cheese in the menu, so that I can ADD regular toppings for my sandwich

### ISSUE THREAD

**Issue by muhamrif** [muhamrif/Whole-Lotta-Sub#5]
- [x] As a USER, I can ADD Regular toppings my sandwich
- [x] As a USER, I can ADD multiple Regular toppings my sandwich

STEPS:

- [x]  Create a RegularTopping class.
- [x]  add the option to add Regular Topping in the ADD SANDWICH menu
- [x]  after USER selects the type of topping, instantiate a RegularTopping object using the user input.
- [x] DIFFERENT TYPES OF REGULAR TOPPINGS:
1. Lettuce
2. Peppers
3. Onions
4. Tomatoes
5. Jalepenos
6. Cucumber
7. Pickles
8. Guacamole
9. Mushrooms

- [x]  use the newly created RegularTopping object for the sandwich object.

**Comment by muhamrif** [comment]
STEPS:

- [ ]  Create a RegularTopping class.
- [ ]  add the option to add Regular Topping in the ADD SANDWICH menu
- [ ]  after USER selects the type of topping, instantiate a RegularTopping object using the user input.
- [ ]  use the newly created RegularTopping object for the sandwich object.

**Comment by akhilsomaiya07** [comment]
DIFFERENT TYPES OF REGULAR TOPPINGS:

- [ ] Lettuce
- [ ] Peppers
- [ ] Onions
- [ ] Tomatoes
- [ ] Jalepenos
- [ ] Cucumber
- [ ] Pickles
- [ ] Guacamole
- [ ] Mushrooms
