### ISSUE TITLE
As a USER,I want to see different options for toppings in the menu, so that I can ADD sides for my sandwich

### ISSUE THREAD

**Issue by muhamrif** [muhamrif/Whole-Lotta-Sub#7]
STEPS:
- [ ]  Create a RegularTopping class.
- [ ]  add the option to add sides in the ADD SANDWICH menu
- [ ] DIFFERENT SIDES FOR BREAD:
1. au jus
2.  sauce
- [ ]  after USER selects the type of sides, instantiate a RegularTopping object using the user input.
- [ ]  use the newly created RegularTopping object for the sandwich object.

**Comment by muhamrif** [comment]
STEPS:

- [ ]  Create a RegularTopping class.
- [ ]  add the option to add sides in the ADD SANDWICH menu
- [ ]  after USER selects the type of sides, instantiate a RegularTopping object using the user input.
- [ ]  use the newly created RegularTopping object for the sandwich object.

**Comment by akhilsomaiya07** [comment]
DIFFERENT SIDES FOR BREAD:

- [ ] au jus
- [ ] sauce
