### ISSUE TITLE
As a USER I can ADD drinks to the order, so I can checkout

### ISSUE THREAD

**Issue by muhamrif** [muhamrif/Whole-Lotta-Sub#9]
- [ ] Ask user which drink and size they would like to add to order from the menu:
- [ ] DIFFERENT VARIETY OF DRINKS:
1. Coco-cola
2. Pepsi
3. Sprite
4. Mountain Dew
- [ ] DIFFERENT PRICES FOR DRINKS:
1. (small - 4") - $2.00
2. (medium - 8") - $2.50
3. (large - 12") - $3.00
- [ ] make the Drink object, and add that to the drinks array which will be used to instantiate the order object.

**Comment by akhilsomaiya07** [comment]
DIFFERENT VARIETY OF DRINKS:

- [ ] Coco-cola
- [ ] Pepsi
- [ ] Sprite
- [ ] Mountain Dew

**Comment by akhilsomaiya07** [comment]
DIFFERENT PRICES FOR DRINKS:

- [ ] (small - 4") - $2.00
- [ ] (medium - 8") - $2.50
- [ ] (large - 12") - $3.00
